##### import neccessary packages

In [1]:
import pandas as pd 
import numpy as np 
import os,sys

# register the 
current_dir=os.getcwd()                     #current working directory
print(current_dir)
parent_dir=os.path.dirname(current_dir)     # Get the parent directory
print(parent_dir)
sys.path.append(parent_dir)

c:\10acadamy\week3\insurance-analysis\notebooks
c:\10acadamy\week3\insurance-analysis

In [2]:
from scripts.general_purpose import GeneralPurpose, InsuranceDataAnalysis

In [4]:
df_insurance=GeneralPurpose.read_dataset('C:/10acadamy/week3/insurance-analysis/dataset/MachineLearningRating_v3.txt',delimiter='|')
# df_insurance.head()

c:\10acadamy\week3\insurance-analysis\scripts\general_purpose.py:8: DtypeWarning: Columns (32,37) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(dsetPath,delimiter=delimiter)

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [25]:
colList=df_insurance.columns

for idx in range(len(colList)):
    print(idx,colList[idx])

0 UnderwrittenCoverID
1 PolicyID
2 TransactionMonth
3 IsVATRegistered
4 Citizenship
5 LegalType
6 Title
7 Language
8 Bank
9 AccountType
10 MaritalStatus
11 Gender
12 Country
13 Province
14 PostalCode
15 MainCrestaZone
16 SubCrestaZone
17 ItemType
18 mmcode
19 VehicleType
20 RegistrationYear
21 make
22 Model
23 Cylinders
24 cubiccapacity
25 kilowatts
26 bodytype
27 NumberOfDoors
28 VehicleIntroDate
29 CustomValueEstimate
30 AlarmImmobiliser
31 TrackingDevice
32 CapitalOutstanding
33 NewVehicle
34 WrittenOff
35 Rebuilt
36 Converted
37 CrossBorder
38 NumberOfVehiclesInFleet
39 SumInsured
40 TermFrequency
41 CalculatedPremiumPerTerm
42 ExcessSelected
43 CoverCategory
44 CoverType
45 CoverGroup
46 Section
47 Product
48 StatutoryClass
49 StatutoryRiskType
50 TotalPremium
51 TotalClaims

In [37]:
# df_insurance['NumberOfVehiclesInFleet']
df_insurance.isnull().all(1)

0          False
1          False
2          False
3          False
4          False
           ...
1000093    False
1000094    False
1000095    False
1000096    False
1000097    False
Length: 1000098, dtype: bool